### ISSUE TITLE
Question: what is this game a mod of? 

### ISSUE THREAD

**Issue by fusion809** [CombinE88/Medieval-Warfare#12]
Hi,

The only game with "Medieval Warfare" in its name that I was able to find was [Chivalry: Medieval Warfare](https://en.wikipedia.org/wiki/Chivalry:_Medieval_Warfare), but that uses 3D graphics, to my understanding, which the OpenRA game engine does not support. So I suspect that is not it, but as I'm planning on providing a package for it for openSUSE Tumbleweed I've got to write a brief description of this game, so I need to know what it is a mod of. 

Thanks for your time,
Brenton

**Comment by abcdefg30** [comment]
@CombinE88 did all the artwork and concepts himself. As far as I know, this mod isn't based off of any already exsting game(s).

**Comment by fusion809** [comment]
Oh, well that makes it even more impressive. Good to know, thanks!

**Comment by fusion809** [comment]
The OBS package is here if anyone is interested: https://build.opensuse.org/package/show/home:fusion809/openra-mw, follow the "Download package" link for where to download the package itself.
