### ISSUE TITLE
Please provide the AppImage for download on GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [CombinE88/Medieval-Warfare#9]
An AppImage gets built:

https://github.com/CombinE88/Medieval-Warfare/blob/e35cd746b0dd639edbe49eb9d94c8e796555fcdc/.travis.yml#L33

Can you please please provide it for download on GitHub Releases?

https://github.com/probonopd/uploadtool is an easy way to automate this.

**Comment by CombinEC-R** [comment]
done and fixed with 
https://github.com/CombinE88/Medieval-Warfare/commit/a268e59c69a8b7bd913991c959d5c6ca9dce9763
